### PR TITLE
Update CI example

### PR DESCRIPTION
**Pull request by OliverJAsh**
# Problem

This example seemed to be outdated, so I updated it. (The object doesn't actually have the shape the example suggests it does.)

# Solution

Explain your approach. Sometimes it helps to justify your approach against some others that you didn't choose to explain why yours is better.

# TODO

- [ ] 🤓 Add & update tests (always try to _increase_ test coverage)
- [ ] 🔬 Ensure CI is passing (`yarn lint:ci`, `yarn test`, `yarn tsc:ci`)
- [ ] 📖 Update relevant documentation

### CODE REVIEW

**Comment by OliverJAsh** [comment]
Ah, just realised that the docs are correct, but they don't reflect the latest version that's on npm. This commit hasn't been published yet: https://github.com/paularmstrong/build-tracker/commit/23ac9f7d45a27e3063fd9bdfa55759bf7a970fcc#diff-3ebd3c0d7bc0a813b71e1aae5f610dbc.

**Comment by paularmstrong** [comment]
> Ah, just realised that the docs are correct, but they don't reflect the latest version that's on npm. This commit hasn't been published yet: [23ac9f7#diff-3ebd3c0d7bc0a813b71e1aae5f610dbc](https://github.com/paularmstrong/build-tracker/commit/23ac9f7d45a27e3063fd9bdfa55759bf7a970fcc#diff-3ebd3c0d7bc0a813b71e1aae5f610dbc).

Whoops. I'll publish a new version once the other couple PRs you've got are in.

**Comment by OliverJAsh** [comment]
@paularmstrong Thanks for merging all my PRs! When you get a chance, would you mind doing an npm release? I'd really appreciate that ❤️

**Comment by paularmstrong** [comment]
Yep! Doing it soon. Was just working on trying to figure out why your PRs didn't get auto-labeled by the github actions,  despite them running without errors. (and also wanted to double check on this PR)

**Comment by paularmstrong** [comment]
Everything should be updated to `1.0.0-beta.3`!

**Pull request closed without merging**
